### ISSUE TITLE
Make introcite settabel on per-entry basis

### ISSUE THREAD

**Issue by denismaier** [moewew/biblatex-ext#13]
Sometimes I want to have the shorthand in the bibliography. In `biblatex-dw` I can use the option `shorthandinbib` that prints shorthands at the beginning of the respective entry. I thought I could use introcite for this, but it seems that this option is not usable for single entries. Would it be an option to make introcite settable on a per-entry basis?

**Comment by demai** [comment]
Absolutely, `shorthandinbib` is much nicer. Would it be an option to add this to the extended standard styles? I know that I could use the code from `biblatex-dw` in my preamble, but I would prefer a cleaner preamble, and I also think that this might be a very useful extension.

(I guess you are aware of that, but I want to add that the code in `biblatex-dw` is actually a bit more complete. The code in your example will output all shorthands in the bibliography. In `biblatex-dw` it is possible to enable`shorthandinbib` for individual entries only or for all entries with shorthands. Also `biblatex-dw` checks whether we are in the bibliography or in the list of shorthands. Obviously, we wouldn't want the shorthand printed twice in the list of shorthands.)

**Comment by moewew** [comment]
https://github.com/moewew/biblatex-ext/commit/2b0a7df6237cecd54e953ba185d32431bf43e7bc enables `introcite` on a per-entry and per-type level. As mentioned above only `introcite=plain` can be guaranteed to work in those situations, so `introcite=label` issues a warning when used at those levels.

I'm a bit on the fence whether or not I should implement something like `biblatex-dw`'s `shorthandinbib`. Despite the details you rightfully pointed out I still believe that for the most part it is easy to recreate what that option does with a few lines of code, so I don't think that it warrants inclusion in `biblatex-ext`. On the other hand I don't quite like the solution `biblatex-dw` took for dealing with the 'detail' of not printing the shorthand twice in the list of shorthands, but I have nothing better to offer myself.
