### ISSUE TITLE
Please split type+number between patent and report

### ISSUE THREAD

**Issue by bastien-roucaries** [moewew/biblatex-ext#26]
Hi,

I want to add openaccess to patent (some patents are openacess) and I want to implement click on number in order to go to the patent register. It is hard to do if type+number are shared between patent and report.

Bastien

**Comment by moewew** [comment]
Hmm, yeah I can see that `@patent` is a bit special. But I have to think about this. *In general* I don't think it is that great of an idea to make too many bibmacros type-specific if they actually do the same thing.

For now a fairly simple solution is
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}
\usepackage{xcolor}
\usepackage[backend=biber, style=ext-authoryear]{biblatex}


\letbibmacro{type+number:*}{type+number}
\newbibmacro{type+number:patent}{%
  \printtext{\color{red}Some stuff specific to patents}
  \setunit{\addspace}%
  \printfield{type}%
  \setunit*{\addspace}%
  \printfield{number}}

\renewbibmacro*{type+number}{%
  \ifbibmacroundef{type+number:\thefield{entrytype}}
    {\usebibmacro{type+number:*}}
    {\usebibmacro*{type+number:\thefield{entrytype}}}%
}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,almendro,chiu,padhye,kowalik,laufenberg,sorace}

\printbibliography
\end{document}
```
which I find a very useful idiom in general.

**Comment by bastien-roucaries** [comment]
I really like the * stuff... This should be pushed or at least documented

**Comment by moewew** [comment]
Sure, we can advertise this in the docs (https://github.com/plk/biblatex/commit/aa5b03904d697ebe0b28a70907f95d4d52908517), but realistically, I only expect people to find this if they already know it.

**Comment by bastien-roucaries** [comment]
Perfect
