### ISSUE TITLE
Inner cite delims still ignored by bbx@xrefcite 

### ISSUE THREAD

**Issue by ebouna** [moewew/biblatex-ext#30]
As pointed out in https://github.com/moewew/biblatex-ext/issues/29, `citexref` used to ignore the inner cite delims in certain styles. I am using biblatex-ext with the style `ext-authoryear` and the problem unfortunately seems to persist even though I have just updated all packages. Consider the following MWE: 

```
\begin{filecontents}{mabib.bib}
@inbook{inbook,
  author   = {Schreiberling, Ferdi},
  crossref = {book},
  pages    = {1--10},
  title    = {Testing the Title},
}

@inproceedings{inproc2,
  author   = {Tester, Auth},
  crossref = {proc1},
  pages    = {10--20},
  title    = {Testing the second Title},
}
@book{book,
  editor    = {Senor Editor and Senora Editora},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013},
  shorthand = {PR2013}
}
@inproceedings{inproc3,
  author    = {Toaster, Auth},
  publisher = {Nother Publisher},
  title     = {In Some Other Proceedings},
  maintitle = {Main Title of Other Proceedings},
  year      = {2001},
}
@proceedings{proc1,
  editor    = {Orban, Alba},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013}
}

\end{filecontents}

\documentclass{article}
\usepackage[backend=biber,style=ext-authoryear, citexref=true, innamebeforetitle=true, mergedate=maximum, backend=biber]{biblatex}

\defbibcheck{noshorthand}{%
\iffieldundef{shorthand}{}{\skipentry}%
}

\addbibresource{mabib.bib}


\begin{document}
Test \cite{inbook} and \cite{inproc2} and \cite{inproc3} and the great \cite{book} and \cite{proc1}

\printbibheading[heading=bibintoc,title={Literaturverzeichnis}]

\printshorthands[title={Literarische Quellen, anonym erschienene Quellen und Sprachwörterbücher}]

\printbibliography[heading=subbibliography,title={Sonstige Quellen und Fachliteratur},check=noshorthand]
\end{document}
```
Here when inproc2 (Tester 2013) is cited in the bibliography, there are still no parentheses around the year "2013" in the cross reference, i.e. the parent, Orban (2013), that is referred to:

![grafik](https://user-images.githubusercontent.com/82314717/169873343-6b12177f-2f4a-45be-ad40-0667646b2f41.png)

Could you sugggest me some code that would allow me to put the publication year in parentheses even when the publication appears in a crossference? I've seen the fix in commit `d1b4ecb`, but, unfortunately, I am not able to adapt it and to convert it to some equivalent code I could put in my latex preamble. 
Thanks a lot for your help in advance.

**Comment by moewew** [comment]
I get "Orban (2013)" when I actually declare any delimiters. Note that you need to undeclare the delimiter context alias first, otherwise the alias takes effect precedence over the actual definitions.

```latex
\documentclass{article}
\usepackage[
  backend=biber,
  style=ext-authoryear,
  citexref=true,
  innamebeforetitle=true,
  mergedate=maximum,
  backend=biber,
]{biblatex}

\UndeclareDelimcontextAlias{bbx@xrefcite}
\DeclareInnerCiteDelims{bbx@xrefcite}{\bibopenparen}{\bibcloseparen}

\defbibcheck{noshorthand}{%
  \iffieldundef{shorthand}{}{\skipentry}%
}

\begin{filecontents}{\jobname.bib}
@inbook{inbook,
  author   = {Schreiberling, Ferdi},
  crossref = {book},
  pages    = {1--10},
  title    = {Testing the Title},
}
@inproceedings{inproc2,
  author   = {Tester, Auth},
  crossref = {proc1},
  pages    = {10--20},
  title    = {Testing the second Title},
}
@book{book,
  editor    = {Senor Editor and Senora Editora},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013},
  shorthand = {PR2013}
}
@inproceedings{inproc3,
  author    = {Toaster, Auth},
  publisher = {Nother Publisher},
  title     = {In Some Other Proceedings},
  maintitle = {Main Title of Other Proceedings},
  year      = {2001},
}
@proceedings{proc1,
  editor    = {Orban, Alba},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013}
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
Test \cite{inbook} and \cite{inproc2} and \cite{inproc3} and the great \cite{book} and \cite{proc1}

\printbibheading[heading=bibintoc,title={Literaturverzeichnis}]

\printshorthands[heading=subbibliography, title={Literarische Quellen, anonym erschienene Quellen und Sprachwörterbücher}]

\printbibliography[heading=subbibliography,title={Sonstige Quellen und Fachliteratur},check=noshorthand]
\end{document}
```
> Tester, Auth (2013). “Testing the second Title”. In: Orban (2013), pp. 10–20.

![Screenshot of the output (including the relevant portion reproduced above)](https://user-images.githubusercontent.com/6755835/169877997-028d7732-e5f2-480b-95d9-31881cb1eef6.png)

**Comment by ebouna** [comment]
Thanks a lot for this advice.
But it is a bit strange: I have already tried myself adding 
```
\UndeclareDelimcontextAlias{bbx@xrefcite}
\DeclareInnerCiteDelims{bbx@xrefcite}{\bibopenparen}{\bibcloseparen}
``` 
(I think I found the code snippet in one of your posts on the internet). 
And now, I tried again on my own computer and with the same MWE as above on Overleaf. While on my own computer there is no warning issued and unfortunately no effect visible (no parentheses), Overleaf throws a warning:
 ```
l.4 \UndeclareDelimcontextAlias    {bbx@xrefcite} 
The control sequence at the end of the top line of your error message was never \def'ed. 
``` 
and it produces no parentheses around "2013", either. 
I'm not getting what I am doing wrong.

**Comment by moewew** [comment]
Overleaf does not always have the newest versions of LaTeX packages available on the system.

If I choose (cf. https://www.overleaf.com/blog/new-feature-select-your-tex-live-compiler-version) "TeX Live 2021", I get `biblatex-ext` v0.13. Then `\UndeclareDelimcontextAlias` does not error, but the parentheses do not occur due to #29. In that case replicating the fix https://github.com/moewew/biblatex-ext/commit/d1b4ecbbacd4fb161d63f656c9be687d887ec242 for `ext-authoryear.cbx` as in
```latex
\documentclass{article}
\usepackage[
  backend=biber,
  style=ext-authoryear,
  citexref=true,
  innamebeforetitle=true,
  mergedate=maximum,
  backend=biber,
]{biblatex}

\makeatletter
\DeclareFieldFormat{extblx@innerbbx@xrefcitedelims}{%
  \csuse{mkinner\blx@delimcontext delims}{#1}}
\makeatother

\UndeclareDelimcontextAlias{bbx@xrefcite}
\DeclareInnerCiteDelims{bbx@xrefcite}{\bibopenparen}{\bibcloseparen}

\defbibcheck{noshorthand}{%
  \iffieldundef{shorthand}{}{\skipentry}%
}

\begin{filecontents}{\jobname.bib}
@inbook{inbook,
  author   = {Schreiberling, Ferdi},
  crossref = {book},
  pages    = {1--10},
  title    = {Testing the Title},
}
@inproceedings{inproc2,
  author   = {Tester, Auth},
  crossref = {proc1},
  pages    = {10--20},
  title    = {Testing the second Title},
}
@book{book,
  editor    = {Senor Editor and Senora Editora},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013},
  shorthand = {PR2013}
}
@inproceedings{inproc3,
  author    = {Toaster, Auth},
  publisher = {Nother Publisher},
  title     = {In Some Other Proceedings},
  maintitle = {Main Title of Other Proceedings},
  year      = {2001},
}
@proceedings{proc1,
  editor    = {Orban, Alba},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013}
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
Test \cite{inbook} and \cite{inproc2} and \cite{inproc3} and the great \cite{book} and \cite{proc1}

\printbibheading[heading=bibintoc,title={Literaturverzeichnis}]

\printshorthands[heading=subbibliography, title={Literarische Quellen, anonym erschienene Quellen und Sprachwörterbücher}]

\printbibliography[heading=subbibliography,title={Sonstige Quellen und Fachliteratur},check=noshorthand]
\end{document}
```
works.

But if you are still on an older TeX Live from Overleaf (possibly because you are using an Overleaf system provided by your institution and not Overleaf directly) additional fixes and definitions might be needed.

Same goes for your local installation. If it is fully up-to-date you should be able to replicate the exact image I posted above from the shown code. But if your system is not fully updated (maybe it is not even updatable: TeX Live is frozen yearly and you basically have to install a new system each year to stay updated; the TeX live that comes from `apt`/`apt-get` in Ubuntu installations is also frozen), that might mean your local installation does not have the fix either. Please share the complete `.log` file of running the example from my first comment https://github.com/moewew/biblatex-ext/issues/30#issuecomment-1134967289 so we can see the package versions.

**Comment by denismaier** [comment]
> Overleaf does not always have the newest versions of LaTeX packages available on the system.

That's a nice euphemism... ;-)

**Comment by ebouna** [comment]
Thanks a lot, @moewew: I was able now to produce the desired result using your second code version in a MWE. Unfortunately, this, however, caused some new BibLaTeX(-ext) problems which I did not foresee. Moreover, my larger original LaTeX file still seems to resist accepting the solution: and I still have to figure out what prevents the parentheses there to show up. I will go on investigating the case, let you know about how I got on and also send you a log file as soon as possible from a LaTeX compilation of the above MWE. BTW, the log from the LaTeX compilation of the original document  I am writing says: TexLive 2022 and BibLaTeX 0.15v and now I was also able to update the LaTeX packages.

**Comment by ebouna** [comment]
[test.log](https://github.com/moewew/biblatex-ext/files/8766340/test.log)
I uploaded the log. My MWE now also runs normally (hurray): now I will start to figure out where in original file the problem is hidden.  One minor correction regarding my preceding comment: it's `ext-authoryear.bbx 2022/03/06 v0.15` what the log says, I forgot the `ext-` with BibLaTex.

**Comment by ebouna** [comment]
And now I checked it seems even to work without:
```
\makeatletter
\DeclareFieldFormat{extblx@innerbbx@xrefcitedelims}{%
  \csuse{mkinner\blx@delimcontext delims}{#1}}
\makeatother
```
Though I do not understand completely why all this did not work this morning when I had already updated the packages. Once more thank you very much, @moewew (and also thanks @denismaier for your help).

**Comment by moewew** [comment]
Yes, with v0.15 you should not need the code between `\makeatletter...\makeatother`, since #29 was resolved in v0.14.

Do I take it that your last comment means you managed to get the desired output in both the MWE and your actual (much) larger document?

**Comment by ebouna** [comment]
Unfortunately, the problem with the original larger document remains. But I think after some testing, I have realized in which part the issue arises. I attached the "original" file with the complete preamble, but a body that has only 4 citations to illustrate the problem. I also attached the bib-file I used to compile (with 4 entries) and the corresponding log. (tex and bib files had to be renamed to txt files to make it possible to upload them.)
[OrigFile_testLatex.txt](https://github.com/moewew/biblatex-ext/files/8774384/OrigFile_testLatex.txt)
[mybib.txt](https://github.com/moewew/biblatex-ext/files/8774388/mybib.txt)
[OrigFile_testLatex.log](https://github.com/moewew/biblatex-ext/files/8774422/OrigFile_testLatex.log)

As I mentioned I think now I have an idea where the issue comes from. It is probably the following part: 
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\DeclareFieldFormat{origdate}{\mkbibbrackets{#1}}%%%PROBABLE SOURCE OF PROBLEM:Get origdate and date for reprints such as in Klaić [1942] 2008%%%
\renewbibmacro*{cite:labeldate+extradate}{%
\iffieldundef{origyear}
{}
{\printorigdate
\setunit{\addspace}}%
\iffieldundef{labelyear}
{}
{\printtext[bibhyperref]{\printlabeldateextra}}}
\DeclareCiteCommand{\citeorigyear}
{\boolfalse{citetracker}%
\boolfalse{pagetracker}%
\usebibmacro{prenote}}
{\printfield{origyear}}
{\multicitedelim}
{\usebibmacro{postnote}}
\renewbibmacro*{date+extradate}{%
\iffieldundef{origyear}
{}
{\printorigdate
\setunit{\addspace}}%
\iffieldundef{labelyear}
{}
{\printtext[parens]{%
\iflabeldateisdate
{\printdateextra}
{\printlabeldateextra}}}}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
With the preceding code snippet, which I found on the internet, I try to get the origdate and date data types into my bibliography to be displayed after each other in the following form: `[1942] 2008`, i.e., first origdate in square brackets, then the year of publication.  When I leave out the code snippet given above from my preamble, the parentheses seem to reappear. But I am not capable myself of  rewriting the code above to correct it. Could you maybe give me a hint or is there a better way to get a combination of origdate and date whenever there is an additional origdate?
(When attaching the files above, I left out the indexstyle file since the LaTeX file seems to compile even without it, but I can add it if it's necessary.)

**Comment by moewew** [comment]
Yeah, the problem is
```latex
\renewbibmacro*{cite:labeldate+extradate}{%
  \iffieldundef{origyear}
    {}
    {\printorigdate
     \setunit{\addspace}}%
  \iffieldundef{labelyear}
    {}
    {\printtext[bibhyperref]{\printlabeldateextra}}}
```
because it is based on [the `authoryear.cbx` definition of `cite:labeldate+extradate` (ll. 56-59)](https://github.com/plk/biblatex/blob/2d49764f97fd4295a5166e94acc2b094f7952190/tex/latex/biblatex/cbx/authoryear.cbx#L56-L59)
```latex
\newbibmacro*{cite:labeldate+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[bibhyperref]{\printlabeldateextra}}}
```
and not on the `ext-authoyear.cbx` definition

https://github.com/moewew/biblatex-ext/blob/3067be9a3bc82cc8d35210e46c09b70b8024dc36/ext-authoryear.cbx#L33-L39

In particular the code effectively disables inner cite delims.

You need to combine the
```latex
\printorigdate
\setunit*{\addspace}%
```
that you added with the definition from `ext-authoyear.cbx`. There are several ways depending on the bracket nesting you desire, I'll just show one below.

Similarly, your redefinition of `date+extradate` is based on the `authoryear.bbx` definition and not the `ext-authoryear-common.bbx` definition, so would not support the `biblabeldate` field format as documented. Furthermore, the functionality of the `mergedate` option is impacted (this is actually not easy to remedy, so I did not attempt to do so - just a warning), because it relies on redefining the bibmacro `date+extradate`.

A few additional comments about your `biblatex` code
* `finalnamedelim` is a context-sensitive delimiter now and should be redefined with `\DeclareDelimFormat`. `biblatex` generally prefers commands like `\addslash` over `/`.
* Do not use `\DefineBibliographyStrings{ngerman}{page={},pages={}}%` to suppress "p."/"pp.". It is much better to redefine the relevant field formats for `postnote` and `pages`.
* The redefinition of the `author` bibmacro wipes out the years in the bibliography, because it is based on `biblatex.def` and not `authoryear.bbx`.
* You don't have to redefine `volume+number+eid` to change the volume/number format if you use `biblatex-ext`. You can use `\volnumdelim` and friends.

I also find the code incredibly hard to read, because there is no indentation. But I guess if it works for you ... (I had to restore some indentation in the code I posted below - otherwise I would have struggled to understand what's going on.) It's also somewhat difficult to keep track of things if in between the `biblatex` modifications there are other unrelated definitions.

Here is a slightly modified version of your `biblatex` code that should hopefully work as expected. It restores some of `biblatex-ext`'s features that were previously overwritten and makes use of `biblatex-ext` features where appropriate.

```latex
\documentclass{article}
\usepackage[
  backend=biber,
  style=ext-authoryear,
  citexref=true,
  innamebeforetitle=true,
  mergedate=maximum,
  backend=biber,
]{biblatex}

\DeclareNameAlias{sortname}{family-given}
\DeclareDelimFormat{finalnamedelim}{\addslash\space}

\makeatletter
\DeclareFieldFormat{origdate}{\mkbibbrackets{#1}}
\renewbibmacro*{cite:labeldate+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[extblx@inner\blx@delimcontext delims]{%
       \printtext[bibhyperref]{%
         \printorigdate
         \setunit*{\addspace}%
         \printtext[\blx@delimcontext labeldate]{%
           \printlabeldateextra}}}}}

\renewbibmacro*{date+extradate}{%
  \printorigdate
  \setunit*{\addspace}
  \iffieldundef{labelyear}
    {}
    {\printtext[\blx@delimcontext labeldate]{%
       \iflabeldateisdate
         {\printdateextra}
         {\printlabeldateextra}}}}%

\renewbibmacro*{author}{%
  \ifboolexpr{
    test \ifuseauthor
    and
    not test {\ifnameundef{author}}
  }
    {\usebibmacro{bbx:dashcheck}
       {\bibnamedash}
       {\usebibmacro{bbx:savehash}%
        \printnames{author}%
        \iffieldundef{authortype}
          {\setunit{\printdelim{nameyeardelim}}}
          {\setunit{\printdelim{authortypedelim}}}}%
     \iffieldundef{nameaddon}
       {}
       {\setunit{\addspace}%
        \printtext[brackets]{%
          \printtext{=\addspace}%
          \printfield{nameaddon}}}%
     \iffieldundef{authortype}
       {}
       {\usebibmacro{authorstrg}%
        \setunit{\printdelim{nameyeardelim}}}}%
    {\global\undef\bbx@lasthash
     \usebibmacro{labeltitle}%
     \setunit*{\printdelim{nonameyeardelim}}}%
  \usebibmacro{date+extradate}}
\makeatother

\DeclareDelimFormat[bib,biblist]{nametitledelim}{\addcolon\space}

\DeclareFieldFormat[article,inbook,incollection,inproceedings,patent,thesis,unpublished]{title}{#1\isdot}

\renewcommand*{\volnumdelim}{\addspace}
\DeclareFieldFormat[article,periodical]{number}{\mkbibparens{#1}}

\DeclareFieldFormat[book,inbook,incollection,collection]{series}{\mkbibemph{#1}}% customize series and number
\renewbibmacro*{series+number}{%
  \iffieldundef{series}
    {}
    {\printtext[parens]{%
       \printtext{=\addspace}%
       \printfield{series}%
       \setunit*{\addnbspace}%
       \printfield{number}%
       \printtext{\addperiod}}
     \nopunct}}

\DeclareFieldFormat{postnote}{\mknormrange{#1}}
\DeclareFieldFormat{volcitepages}{\mknormrange{#1}}
\DeclareFieldFormat{pages}{#1}

\UndeclareDelimcontextAlias{bbx@xrefcite}
\DeclareInnerCiteDelims{bbx@xrefcite}{\bibopenparen}{\bibcloseparen}

\NewBibliographyString{subverbo}%new locators subverbo(s)
\NewBibliographyString{subverbos}
\DefineBibliographyStrings{ngerman}{subverbo = {s.\,v.}, subverbos = {s.\,v.}}

\renewcommand*{\bibfont}{\normalfont\small}

\defbibcheck{noshorthand}{%
  \iffieldundef{shorthand}{}{\skipentry}%
}

\begin{filecontents}{\jobname.bib}
@inbook{inbook,
  author   = {Schreiberling, Ferdi},
  origdate = {1875},
  crossref = {book},
  pages    = {1--10},
  title    = {Testing the Title},
}
@inproceedings{inproc2,
  author   = {Tester, Auth},
  crossref = {proc1},
  pages    = {10--20},
  title    = {Testing the second Title},
}
@book{book,
  editor    = {Senor Editor and Senora Editora},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013},
  shorthand = {PR2013}
}
@inproceedings{inproc3,
  author    = {Toaster, Auth},
  publisher = {Nother Publisher},
  title     = {In Some Other Proceedings},
  maintitle = {Main Title of Other Proceedings},
  year      = {2001},
}
@proceedings{proc1,
  editor    = {Orban, Alba},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
Test \cite{inbook,inproc2,inproc3,book,proc1}

Test \textcite{inbook}
and \textcite{inproc2}
and \textcite{inproc3}
and the great \textcite{book}
and \textcite{proc1}

\autocite{sigfridsson,coleridge}

\printbibheading[heading=bibintoc,title={Literaturverzeichnis}]
\printshorthands[heading=subbibliography, title={Literarische Quellen, anonym erschienene Quellen und Sprachwörterbücher}]
\printbibliography[heading=subbibliography,title={Sonstige Quellen und Fachliteratur},check=noshorthand]
\end{document}
```

**Comment by ebouna** [comment]
Thanks a lot! This is great, extremely helpful! I am trying out the solution inside my original file and let you know in the next days, i.e., hopefully at the latest on Sunday. 
And sorry, of course, for, among other things, the missing indentation in the latex file. This is something I completely forgot to do before sending the file to you.

**Comment by moewew** [comment]
Don't worry about the indentation. I am just surprised whenever I see "flat" documents without any indentation for the preamble code that's longer than a couple of lines. I find that indentation helps me understand the code so much better, so I always (have to!) add it and always try to advertise it to people who posted "flat" code.

**Comment by ebouna** [comment]
I have been testing. I noticed that unfortunately my hyperref-links in the bibliography have partly gone, i.e. whenever at the beginning  of an bibliography entry the year of publication is given: 
![grafik](https://user-images.githubusercontent.com/82314717/170882184-2d88f68d-afff-42df-ab6f-82d6eea3d8f4.png)
That is, the first "2018" should also have a hyperref link as the second one in the 2nd line on the above image. In the main text, the hyperref links are still there.
Note that the 2nd "2018" on the image above now has its brackets (thanks a lot!). 

Also whenever I insert "\pno" to get the "NewBibliographystring" `subverbo`, this is now rendered as "S." (in a German text) and not as "s. v." as it should be rendered and as it used to be rendered.
Could you give me a hint how to correct these two new faults, too?

**Comment by moewew** [comment]
Where would the hyperlink of the first 2018 lead to, though? The only thing that would make sense to me is to exactly this position. But your reader is already there. (It wouldn't be impossible to add the link, but to me it just doesn't make sense. None of the styles I know do this.)

As for the `\pno`: I'm guessing you are somewhat abusing the page range formatting mechanism for `subverbo`. Can't you just define
```latex
\newcommand*{\subv}{\bibstring{subverbo}}
\newcommand*{\subvv}{\bibstring{subverbos}}
```
and use those instead of `\pno`? (This would be more semantical anyway, since I'm assuming what normally follows a "sub verbo" is a word and not a page number.)

**Comment by ebouna** [comment]
I see that you are perfectly right in both cases. Thank you for your explanation. Everything else works as expected now. There is only one other thing I wanted to ask about: the hyperref-link between the years of publication in the main text and the 2nd part of the bibliography (the one without shorthands) work as expected. However, the hyperref-links between the shorthands in the main text and the shorthand list in the bibliography do not work. These latter links always lead instead to the last page of the document. Could one correct this, too?

**Comment by moewew** [comment]
Try
```latex
\makeatletter
\AtEveryBiblistitem{shorthand}{\blx@anchor}
\makeatother

```

**Comment by ebouna** [comment]
It works! Thanks a lot for all your help. You're great!

**Comment by ebouna** [comment]
Do you think the links still do not work properly?

**Comment by moewew** [comment]
Sorry, I don't think I understand.

As far as I can tell all links work in the following example that uses the trick shown above.
```latex
\documentclass{article}
\usepackage[
  backend=biber,
  style=ext-authoryear,
  citexref=true,
  innamebeforetitle=true,
  mergedate=maximum,
  backend=biber,
]{biblatex}
\usepackage{hyperref}

\DeclareNameAlias{sortname}{family-given}
\DeclareDelimFormat{finalnamedelim}{\addslash\space}

\makeatletter
\DeclareFieldFormat{origdate}{\mkbibbrackets{#1}}
\renewbibmacro*{cite:labeldate+extradate}{%
  \iffieldundef{labelyear}
    {}
    {\printtext[extblx@inner\blx@delimcontext delims]{%
       \printtext[bibhyperref]{%
         \printorigdate
         \setunit*{\addspace}%
         \printtext[\blx@delimcontext labeldate]{%
           \printlabeldateextra}}}}}

\renewbibmacro*{date+extradate}{%
  \printorigdate
  \setunit*{\addspace}
  \iffieldundef{labelyear}
    {}
    {\printtext[\blx@delimcontext labeldate]{%
       \iflabeldateisdate
         {\printdateextra}
         {\printlabeldateextra}}}}%

\renewbibmacro*{author}{%
  \ifboolexpr{
    test \ifuseauthor
    and
    not test {\ifnameundef{author}}
  }
    {\usebibmacro{bbx:dashcheck}
       {\bibnamedash}
       {\usebibmacro{bbx:savehash}%
        \printnames{author}%
        \iffieldundef{authortype}
          {\setunit{\printdelim{nameyeardelim}}}
          {\setunit{\printdelim{authortypedelim}}}}%
     \iffieldundef{nameaddon}
       {}
       {\setunit{\addspace}%
        \printtext[brackets]{%
          \printtext{=\addspace}%
          \printfield{nameaddon}}}%
     \iffieldundef{authortype}
       {}
       {\usebibmacro{authorstrg}%
        \setunit{\printdelim{nameyeardelim}}}}%
    {\global\undef\bbx@lasthash
     \usebibmacro{labeltitle}%
     \setunit*{\printdelim{nonameyeardelim}}}%
  \usebibmacro{date+extradate}}
\makeatother

\DeclareDelimFormat[bib,biblist]{nametitledelim}{\addcolon\space}

\DeclareFieldFormat[article,inbook,incollection,inproceedings,patent,thesis,unpublished]{title}{#1\isdot}

\renewcommand*{\volnumdelim}{\addspace}
\DeclareFieldFormat[article,periodical]{number}{\mkbibparens{#1}}

\DeclareFieldFormat[book,inbook,incollection,collection]{series}{\mkbibemph{#1}}% customize series and number
\renewbibmacro*{series+number}{%
  \iffieldundef{series}
    {}
    {\printtext[parens]{%
       \printtext{=\addspace}%
       \printfield{series}%
       \setunit*{\addnbspace}%
       \printfield{number}%
       \printtext{\addperiod}}
     \nopunct}}

\DeclareFieldFormat{postnote}{\mknormrange{#1}}
\DeclareFieldFormat{volcitepages}{\mknormrange{#1}}
\DeclareFieldFormat{pages}{#1}

\UndeclareDelimcontextAlias{bbx@xrefcite}
\DeclareInnerCiteDelims{bbx@xrefcite}{\bibopenparen}{\bibcloseparen}

\NewBibliographyString{subverbo}%new locators subverbo(s)
\NewBibliographyString{subverbos}
\DefineBibliographyStrings{ngerman}{subverbo = {s.\,v.}, subverbos = {s.\,v.}}

\renewcommand*{\bibfont}{\normalfont\small}

\defbibcheck{noshorthand}{%
  \iffieldundef{shorthand}{}{\skipentry}%
}

\makeatletter
\AtEveryBiblistitem{shorthand}{\blx@anchor}
\makeatother

\begin{filecontents}{\jobname.bib}
@inbook{inbook,
  author   = {Schreiberling, Ferdi},
  origdate = {1875},
  crossref = {book},
  pages    = {1--10},
  title    = {Testing the Title},
}
@inproceedings{inproc2,
  author   = {Tester, Auth},
  crossref = {proc1},
  pages    = {10--20},
  title    = {Testing the second Title},
}
@book{book,
  editor    = {Senor Editor and Senora Editora},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013},
  shorthand = {PR2013}
}
@inproceedings{inproc3,
  author    = {Toaster, Auth},
  publisher = {Nother Publisher},
  title     = {In Some Other Proceedings},
  maintitle = {Main Title of Other Proceedings},
  year      = {2001},
}
@proceedings{proc1,
  editor    = {Orban, Alba},
  publisher = {Any Publisher},
  title     = {My Proceedings},
  year      = {2013}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
Test \cite{inbook,inproc2,inproc3,book,proc1,kant:kpv}

Test \textcite{inbook}
and \textcite{inproc2}
and \textcite{inproc3}
and the great \textcite{book}
and \textcite{proc1}

\autocite{sigfridsson,coleridge}

\printbibheading[heading=bibintoc,title={Literaturverzeichnis}]
\printshorthands[heading=subbibliography, title={Literarische Quellen, anonym erschienene Quellen und Sprachwörterbücher}]
\printbibliography[heading=subbibliography,title={Sonstige Quellen und Fachliteratur},check=noshorthand]
\end{document}
```

**Comment by ebouna** [comment]
Yes, that is what I tried to say. The links work. I just asked because you added the "invalid" label .

**Comment by moewew** [comment]
I see.

I use labels to classify the issues. For things that turn out to be requests for help and not bug reports or feature requests I use "invalid". As far as I can tell the initial question was either a duplicate of #29 or just an issue with your installation (`biblatex-ext` was not updated correctly). The remainder of the discussion just involved tweaking your preamble code. It did not involve any `biblatex-ext` bugs or formulate any feature requests as far as I can tell.

**Comment by ebouna** [comment]
Yes, I completely agree. Now it becomes clear to me what you meant by "invalid".
