### ISSUE TITLE
 problems of alignment with 'introcite=label'

### ISSUE THREAD

**Issue by matteofg** [moewew/biblatex-ext#39]
No problem if `introcite=label` is set on a global basis.
If `introcite=label` is set on a per-type or on a per-entry basis., there is a problem with the alignment of bibliography entries.
No problem, however, with `introcite=plain`.

Below a mwe:
```
% !TEX encoding = UTF-8 Unicode
% !TEX program = lualatex
% !BIB program = biber

\begin{filecontents}[overwrite]{\jobname.bib}
@article{a,
  author = {Williams, Robert},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2000},
  options = {introcite=label},
}
@article{b,
  author = {Anderson, Thomas},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2010},
}
@article{c,
  author = {Taylor, Charles},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2010},
}
@article{d,
  author = {Wilson, Joseph},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2000},
}
@book{e,
  author = {Smith, James},
  title = {Title of the book},
  date = {2020},
}
\end{filecontents}

\documentclass{article}
\usepackage[style=ext-authoryear]{biblatex}
  \addbibresource{\jobname.bib}
  \ExecuteBibliographyOptions[book]{introcite=label}

\begin{document}
\autocite{a,b,c,d,e}

\printbibliography
\end{document}
```
<img width="649" alt="Screenshot 2023-07-24 at 11 53 02" src="https://github.com/moewew/biblatex-ext/assets/111273603/3d5ad3be-bf33-46f2-95b9-c4a11e8d251f">

**Comment by moewew** [comment]
`introcite=label` needs support in the bibliography environment. As such we need to know "beforehand" if a bibliography is to be printed with `introcite=label,`. This is possible if the option is used globally, but not if it is used on a per-type or per-entry level. That's why officially it is not supported to set the option at the latter two levels. The documentation says

> The option is available globally and on a per-type and per-entry level, where only the values `plain` (and the default `false`) are supported.

The MWE also warns about this. You should get

```
Package biblatex-ext Warning: Value 'introcite=label' not officially supported
(biblatex-ext)                on per-type level.
(biblatex-ext)                It requires setup changes for a complete
(biblatex-ext)                bibliography environment, which can only happen
(biblatex-ext)                globally or per bibliography.
(biblatex-ext)                Using 'introcite=label' anyway, the result might
(biblatex-ext)                be off. You have been warned.
```

and
```
Package biblatex-ext Warning: Value 'introcite=label' not officially supported
(biblatex-ext)                on per-entry level.
(biblatex-ext)                It requires setup changes for a complete
(biblatex-ext)                bibliography environment, which can only happen
(biblatex-ext)                globally or per bibliography.
(biblatex-ext)                Using 'introcite=label' anyway, the result might
(biblatex-ext)                be off. You have been warned.
```

**Comment by matteofg** [comment]
Thank you for your response. Perhaps you could highlight this issue better in the documentation (imho).

Furthermore, the warning says:
`It requires setup changes for a complete bibliography environment, which can only happen globally or per bibliography.`

So, if I set up two different bibliographies, via
```
\printbibliography[type= article]
\printbibliography[type=book]
```
how can I set `introcite=label` _per bibliography_?

**Comment by moewew** [comment]
Alright, let me know if https://github.com/moewew/biblatex-ext/commit/78fe57d90d4c2be7feab72ecbdcf3cae8ae7288a has made it any clearer.

You essentially have to set up `introcite=label,` *before* you call `\printbibliography`. (The per-entry and per-type option handling comes in too late.) This can be done manually as follows.
```latex
\documentclass{article}
\usepackage[style=ext-authoryear]{biblatex}

\ExecuteBibliographyOptions[book]{introcite=label}

\begin{filecontents}{\jobname.bib}
@article{a,
  author = {Williams, Robert},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2000},
}
@article{b,
  author = {Anderson, Thomas},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2010},
}
@article{c,
  author = {Taylor, Charles},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2010},
}
@article{d,
  author = {Wilson, Joseph},
  title = {Title of the article},
  journaltitle = {Journaltitle},
  date = {2000},
}
@book{e,
  author = {Smith, James},
  title = {Title of the book},
  date = {2020},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\autocite{a,b,c,d,e}

\printbibliography[type=article]
\begingroup
\csletcs{extblx@introcite}{extblx@opt@introcite@label}
\printbibliography[type=book]
\endgroup
\end{document}
```

**Comment by matteofg** [comment]
> Alright, let me know if https://github.com/moewew/biblatex-ext/commit/78fe57d90d4c2be7feab72ecbdcf3cae8ae7288a has made it any clearer.

Very well.
```
\begingroup
\csletcs{extblx@introcite}{extblx@opt@introcite@label}
\printbibliography[type=book]
\endgroup
```
Thank you for the solution!
Obviously this is a hard coded way. At this point it would be interesting to be able to use the `introcite=label` option through `\newrefcontext` and `\begin{refcontext}`, like `\newrefcontext[introcite=label]`.

**Comment by moewew** [comment]
I'm in two minds about this. The current implementation of the option means that things would essentially work if it were allowed per-refcontext (not sure about grouping at the moment: that could be an issue). But it does not really *feel* like a per-refcontext option to me. Plus mixing `introcite=label,` with `introcite=false,` bibliographies makes for a pretty inconsistent output, so I'd much rather have users do some manual work so they know that what they are doing is not "officially supported".

**Comment by matteofg** [comment]
> Plus mixing `introcite=label`, with `introcite=false`, bibliographies makes for a pretty inconsistent output

In these terms, even `introcite=plain` with `introcite=false` make the output rather inconsistent.
I think one must assume that if the document author takes action on these issues, he does so _cum grano salis_.

> `introcite=label` needs support in the bibliography environment. As such we need to know "beforehand" if a bibliography is to be printed with `introcite=label`,. This is possible if the option is used globally, but not if it is used on a per-type or per-entry level.

So, the problem is purely technical and I hope it can be solved.
It would be good, for example, to be able to solve the alignment of bibliography by a second run of LaTeX (taking advantage of the .aux file).

**Comment by moewew** [comment]
I don't think I want to implement more local `introcite` at the moment. It just doesn't feel right to me. But for people who must have such a feature the workaround discussed here is available.

In case people really need this I would be interested in seeing real-world examples and explanations why it is necessary. We can always reopen this if demand is high.
