### ISSUE TITLE
Additional space after 'No Date' in bibliography

### ISSUE THREAD

**Issue by tommysalt** [moewew/biblatex-ext#40]
**Description**
The citation in the bibliography adds a space after 'Keine Datumsangabe' (German), 'No Date' (English) as shown in the screenshot.
<img width="500" alt="" src="https://github.com/moewew/biblatex-ext/assets/100965650/b701cafc-22f2-4cb1-a511-ead94e97f229">
In my opinion it shouldn't print 'Keine Datumsangabe' (German), 'No Date' (English) in the first place as it is already clear that no date is given because of n.D. after the author's name.

**To Reproduce**
```
@online{Belastingdienst,
    usera = {{Bürgerservicenummer}},
    author = {{Belastingdienst}},
    title = {{Was ist eine Bürgerservicenummer (BSN)?}},
    url = {https://www.belastingdienst.nl/wps/wcm/connect/bldcontentde/belastingdienst/privatpersonen/sonstige_themen/buergerservicenummer/was_ist_eine_buergerservicenummer_bsn},
    urldate = {2019-02-26},
}
```
I know, it's in German but the content shouldn't matter.

**Expected behaviour**
No additional space and no output in the first place if no date is given. The reader should already be aware that no date is given because it's also stated after the author's name. Similar to how Chicago Style does it.

**Comment by moewew** [comment]
Please try and provide a fully compilable example document when you ask about specific output. That makes it much easier to debug what is going on. `biblatex-ext` offers a number of styles with options and other customisation features. It's rarely clearly obvious which settings are used from a couple of pictures. But of course the setup is crucial to the solution.

In a "usual `biblatex-ext` setup" with `ext-authoryear` I get the following result
```latex
\documentclass[ngerman]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=ext-authoryear]{biblatex}

\begin{filecontents}{\jobname.bib}
@online{Belastingdienst,
  usera   = {Bürgerservicenummer},
  author  = {{Belastingdienst}},
  title   = {Was ist eine Bürgerservicenummer (BSN)?},
  url     = {https://www.belastingdienst.nl/wps/wcm/connect/bldcontentde/belastingdienst/privatpersonen/sonstige_themen/buergerservicenummer/was_ist_eine_buergerservicenummer_bsn},
  urldate = {2019-02-26},
  langid  = {ngerman},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \autocite{Belastingdienst}

\printbibliography
\end{document}
```

> Belastingdienst (2019). Was ist eine Bürgerservicenummer (BSN)? url: https://www.belastingdienst.nl/wps/wcm/connect/bldcontentde/belastingdienst/privatpersonen/sonstige_themen/buergerservicenummer/was_ist_eine_buergerservicenummer_bsn (besucht am 26.02.2019).

![output of the above MWE](https://github.com/moewew/biblatex-ext/assets/6755835/ae330cce-21ec-40e9-a895-03875fa9af84)

This is very different from your screenshot. In particular there is no "keine Datumsangabe". In fact there is no code in `biblatex` or `biblatex-ext` at all that will print "keine Datumsangabe" without additional changes.

From your screenshot I'm guessing you are using FOM-inspired code. If you are using the FOM template from https://github.com/andygrunwald/FOM-LaTeX-Template/issues, file an issue there. If you are using code from elsewhere, complain to that source.

---

BTW: It may or may not be relevant for you, but the URL in the entry did not work for me. I found a similarly named page at https://www.belastingdienst.nl/wps/wcm/connect/de/privatpersonen/inhalt/was-ist-die-buergerservicenummer (which may or may not have the same contents)

**Comment by moewew** [comment]
There has been no reply here for a couple of weeks, so I'm closing this for now. We can reopen the issue if a suitable example document is provided that shows that this indeed an issue with `biblatex-ext`.
