### ISSUE TITLE
Clarify use of `bib(list)labeldate`

### ISSUE THREAD

**Issue by LukasCBossert** [moewew/biblatex-ext#7]
Section 5 of the doc there is the optional feature changing the wrapper of the label date. 
But I think it would be helpful to have a small example how it can be used since ` \DeclareFieldFormat{bib(list)labeldate}{#1}` doesnt work (as one might think following the description).

**Comment by moewew** [comment]
Oh, sorry. That was me trying to be clever. There are two formats `biblabeldate` and `biblistlabeldate`, I thought I might be able to document the two of them together. But I see why it could be confusing. I will change that for the next version.

**Comment by LukasCBossert** [comment]
It is surely clever, but I couldn’t figure it out myself. Thanks for explaining and clarifying in the documentation.
