### ISSUE TITLE
Missing `editortitledelim`?

### ISSUE THREAD

**Issue by LukasCBossert** [moewew/biblatex-ext#8]
As far as I can see it would be a nice option to modify the delimiter between the editor-string `(Hrsg.)` and the title. 
It seems to be `.` by default but sometimes `,` is required instead.

**Comment by LukasCBossert** [comment]
Ok, that was too easy:

`\DeclareFieldFormat{editortype}{\mkbibparens{#1}\addcomma}` 

so probably no need for an `editortitledelim`?!

**Comment by moewew** [comment]
Mhhh, I really don't like `\DeclareFieldFormat{editortype}{\mkbibparens{#1}\addcomma}` including punctuation commands in field formats and thereby bypassing the punctuation trackers is not what I would consider good style. I try to avoid that if at all possible.

What style are you thinking about? For `authoryear` `nameyeardelim` would be triggered between editor and year and all other styles should have `nametitledelim` there. Granted, that is common to all names, not just editor.

Can you please give a short MWE that shows what you are thinking of?

**Comment by LukasCBossert** [comment]
You are right. It was rarer a hack then clean code.

The background of all me asking is that I have been asked for help to code that specific style: https://github.com/LukasCBossert/biblatex-socialscience-huberlin/blob/master/Beispiel_Literaturverzeichnis.pdf

I set up an repository https://github.com/LukasCBossert/biblatex-socialscience-huberlin and there you find a MWE (https://github.com/LukasCBossert/biblatex-socialscience-huberlin/blob/master/socialscience-huberlin.tex). (The thing is that I have to modify `cleanthesis.sty` and overwrite its settings but the style [once it coded] should also work 'standalone')

If you find some time to look at it it would be great.

**Comment by moewew** [comment]
It would be awfully inconsistent to treat an `editor` differently from an `author` in that respect and the PDF does not have an example of an `@inbook`, so I assume you could get away with
```latex
\DeclareDelimFormat[bib,biblist]{innametitledelim}{\addcomma\space}
```

**Comment by LukasCBossert** [comment]
I wasnt aware of `[bib,biblist]` (must have missed it the documentation). I am still gathering more test-data finding out if `@inbook` has to be respected, too.

**Comment by moewew** [comment]
The problem here is that `innametitledelim` (like `nametitledelim`) has different definitions for `bib,biblist` and citation contexts. So in this case we had to redefine the `bib` and `bibllist` context explicitly. Turns out I hadn't documented `innametitledelim` at all. Coming up...

**Comment by moewew** [comment]
Thank you very much for the hint. This is documented now.

I'm running into a bit of a potential name inconsistency/clash here, so I may have to rename some delimiters or macros.... Hopefully not, we'll see...

**Comment by LukasCBossert** [comment]
Very nice.

Well I was rather looking all the examples first searching what I need to modify and then looking at the name. 
So I think having many examples makes it easier to understand the names.

**Comment by moewew** [comment]
`biblatex-ext` v0.3 has been released. Many of your helpful suggestions about the manual have been included (I hope). Thank you for your help.

`editortypedelim` will not be implemented because there are other macros already that should be able to do the job you had in mind consistently for authors and translators as well. That should wrap this issue up.

**Comment by LukasCBossert** [comment]
I thank _you_ for all the help!
