### ISSUE TITLE
Wrong comma before  bibstring `editor`?

### ISSUE THREAD

**Issue by LukasCBossert** [moewew/biblatex-ext#9]
Sorry for bothering you with all this. 

Consider following MWE

```
\documentclass{scrartcl}%
\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@InCollection{Angermuller2014c,
  author    = {Angermuller, Johannes and Macgilchrist, Felicitas},
  title     = {Einleitung: Konzepte und Kontroversen der Diskurstheorie},
  booktitle = {Diskursforschung: ein interdisziplinäres Handbuch},
  editor = {Hans Wurst},
  publisher = {transcript Verlag},
  pages     = {17--20},
  date      = {2014},
  origdate  = {1999}, 
  location  = {Bielefeld},
}
\end{filecontents*}
\usepackage[
  backend=biber,
  style=ext-authoryear,
  innamebeforetitle=true,
  ]{biblatex}
\DeclareFieldFormat{editortype}{\mkbibparens{#1}} 

\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

The combination of `innamebeforetitle=true` and `\DeclareFieldFormat{editortype}{\mkbibparens{#1}}` leads to a comma before the bibstring of `editor`.

<img width="1024" alt="bildschirmfoto 2018-05-23 um 21 40 37" src="https://user-images.githubusercontent.com/12896078/40447214-1ebdf842-5ed2-11e8-96a4-dd7259e10070.png">

If it isn’t a misbehaviour  of the style how can I get rid of the comma?
(see as well: https://github.com/LukasCBossert/biblatex-socialscience-huberlin/issues/2)

**Comment by moewew** [comment]
```latex
\DeclareDelimFormat{editortypedelim}{\addspace} 
```
The style can not automatically detect that you wrap the editor string in parentheses and does not change the `editortypedelim` accordingly. You'll have to do that manually. `editortypedelim` is a feature of the standard styles and is documented in the `biblatex` manual (if only very briefly and not very prominently).

**Comment by LukasCBossert** [comment]
Ok, I have missed that (again). Thank you very much.
